<a href="https://colab.research.google.com/github/Khlybtssh/pytorchLab/blob/main/Pytorch_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch import nn
random_seed

In [ ]:
x = torch.rand(2,3)
x

tensor([[0.0544, 0.6828, 0.5934],
        [0.2893, 0.7315, 0.0159]])

In [ ]:
x_transpose = torch.transpose(x,dim0 =1 ,dim1=-2)
x_transpose

tensor([[0.0544, 0.2893],
        [0.6828, 0.7315],
        [0.5934, 0.0159]])

In [ ]:
x_transpose.reshape(2,3)

tensor([[0.0544, 0.2893, 0.6828],
        [0.7315, 0.5934, 0.0159]])