In [2]:
import torch
from torch import nn
random_seed 

In [20]:
x = torch.rand(4,3)
x

tensor([[0.4013, 0.9536, 0.0139],
        [0.6555, 0.9822, 0.5307],
        [0.2472, 0.8997, 0.2454],
        [0.0324, 0.2165, 0.8113]])

In [21]:
x_transpose = torch.transpose(x,dim0 =1 ,dim1=-2)
x_transpose

tensor([[0.4013, 0.6555, 0.2472, 0.0324],
        [0.9536, 0.9822, 0.8997, 0.2165],
        [0.0139, 0.5307, 0.2454, 0.8113]])

In [35]:
x_transpose.reshape(-1,6)

tensor([[0.4013, 0.6555, 0.2472, 0.0324, 0.9536, 0.9822],
        [0.8997, 0.2165, 0.0139, 0.5307, 0.2454, 0.8113]])

In [56]:
x[:,1:]

tensor([[0.9536, 0.0139],
        [0.9822, 0.5307],
        [0.8997, 0.2454],
        [0.2165, 0.8113]])